"""Seed registry for the 70 OLC Quality Scorecard (Administration of Online Programs) indicator slots.

PROVENANCE OF THIS FILE
-----------------------
* Indicator wording ("text") was transcribed from the FAU OLC Evidence Matrix
  (seed/FAU_OLC_Evidence_Matrix.xlsx, sheet "Evidence Matrix"), which the FAU team built from the
  OLC Quality Scorecard. It has NOT yet been checked against the official QSS PDF because that PDF
  was not supplied with the initial build. text_source records this for every indicator.
* 13 slots (numbered gaps in the matrix) have no wording in any supplied file. Their text is None
  and text_source is "PENDING". The engine will not auto-map evidence to them until the wording is
  loaded (Admin > OLC Rubric: import the QSS PDF, or paste the wording).
* Where the matrix contains two different wordings for the same slot, both are kept
  (text + alt_text) and the conflict is flagged for verification.
* "required", "anchors", "terms", "elements", "artifacts" and "owners" are FAU-team working guidance
  authored for this agent (evidence expectations, search vocabulary, likely owners). They are NOT
  OLC text and are labelled as such in the UI.

Level vocabulary (lowest -> highest):
  INTENT < PROCESS < IMPLEMENTATION < MEASUREMENT < IMPROVEMENT
"required" = the highest level an external reviewer would need to see substantiated.
"""

I, P, M, MEAS, IMP = "INTENT", "PROCESS", "IMPLEMENTATION", "MEASUREMENT", "IMPROVEMENT"

CATEGORIES = [
    ("INS", "Institutional Support", 8),
    ("TEC", "Technology Support", 7),
    ("CDID", "Course Development & Instructional Design", 11),
    ("CS", "Course Structure", 7),
    ("TL", "Teaching & Learning", 4),
    ("FAC", "Faculty Support", 9),
    ("LEA", "Learner Support", 15),
    ("EVA", "Evaluation & Assessment", 9),
]

MATRIX = "FAU OLC Evidence Matrix (transcribed from OLC QSS; verify against QSS PDF)"

# Owner vocabulary (office level only; no individual names).
FAO = "Florida Atlantic Online / COCE"
COCE_ID = "COCE Instructional Design"
COCE_QA = "COCE Quality Assurance"
OESS = "COCE Online Enrollment & Student Success (OESS)"
OIT = "Office of Information Technology (OIT)"
OIT_SEC = "OIT Information Security"
PROV = "Office of the Provost"
FSEN = "Faculty Senate"
IEA = "Institutional Effectiveness & Analysis"
REG = "Office of the Registrar"
FA = "Office of Financial Aid"
LIB = "FAU Libraries"
SAS = "Student Accessibility Services"
SA = "Student Affairs"
CAPS = "Counseling & Psychological Services (CAPS)"
CLASS = "Center for Learning and Student Success (CLASS)"
CAREER = "Career Center"
COLL = "Colleges / Departments"
BUD = "Budget Office"
COMM = "University Communications"
OTD = "Office of Technology Development"
GC = "Office of the General Counsel"
ADM = "Admissions / Enrollment Management"
BOOK = "Bookstore / Course Materials"
FACDEV = "COCE Faculty Development"

INDICATORS = [
    # ------------------------------------------------------------ Institutional Support (8)
    dict(id="INS-01", n=1, required=I,
         text="The institution's mission, value and strategic plan are inclusive of online learning and the structure for delivering online education supports the institution's mission, values and strategic plan.",
         anchors=[r"mission", r"strategic plan", r"vision", r"aspires? to be", r"our mission is"],
         terms=["online", "distance learning", "online learning", "online programs", "align", "structure", "organizational", "reports to", "high-quality"],
         elements={"Mission/strategic plan includes online learning": ["mission", "strategic plan", "vision"],
                   "Organizational structure supports delivery": ["organizational chart", "reports to", "structure", "division", "unit"]},
         artifacts=[(I, "University-level strategic plan / Accountability Plan excerpt that explicitly includes online learning (not only the COCE unit plan)"),
                    (P, "Current organizational chart showing where Florida Atlantic Online / COCE sits and its reporting line to Academic Affairs"),
                    (M, "Evidence the COCE 2025-2030 plan was reviewed/endorsed by the Provost or university leadership (approval memo, presentation, minutes)")],
         owners=[PROV, FAO]),
    dict(id="INS-02", n=2, required=M,
         text="The institution has clearly defined and communicated the strategic value of online learning to all stakeholders (students, faculty, staff, community, etc.).",
         anchors=[r"strategic value", r"value of online", r"communicat", r"promote", r"stakeholder"],
         terms=["online", "students", "faculty", "staff", "community", "listserv", "social media", "web pages", "outreach", "access"],
         elements={"Value defined": ["value", "mission", "vision", "access"],
                   "Communicated to students": ["students"], "Communicated to faculty/staff": ["faculty", "staff"],
                   "Communicated to community": ["community", "public"]},
         artifacts=[(M, "Examples of communications to each stakeholder group (faculty listserv messages, student newsletters, community/website content) with dates and reach"),
                    (M, "Presentations of the online strategy to Deans/Chairs, Faculty Senate or Board of Trustees"),
                    (MEAS, "Reach/engagement metrics for those communications (opens, attendance, page views)")],
         owners=[FAO, COMM]),
    dict(id="INS-03", n=3, required=M,
         text="The institution has a governance structure to enable clear, effective and comprehensive decision making related to online education.",
         anchors=[r"governance", r"approval process", r"decision", r"responsib", r"faculty senate", r"committee"],
         terms=["online", "distance learning", "provost", "curriculum", "program", "registrar", "approve", "dean", "policy"],
         elements={"Documented decision rights": ["responsib", "decision", "approval"],
                   "Governance bodies": ["committee", "senate", "council"],
                   "Operates in practice": ["minutes", "approved on", "meeting"]},
         artifacts=[(P, "Charter/terms of reference for any committee that governs online education decisions (e.g., distance learning advisory committee)"),
                    (M, "Recent minutes or approval records showing online-program decisions moving through Faculty Senate / Provost workflow"),
                    (M, "Decision-rights (RACI) matrix for online program proposals, modality changes, and teach-out plans")],
         owners=[PROV, FSEN, FAO]),
    dict(id="INS-04", n=4, required=IMP,
         text="The institution has a process to enable systematic and continuous improvement related to the administration of online education.",
         anchors=[r"continuous improvement", r"improv", r"assess", r"monitor", r"evaluat", r"survey", r"revised"],
         terms=["data", "survey", "metrics", "retention", "persistence", "dfw", "review", "cycle", "annual", "revision"],
         elements={"Defined improvement process": ["process", "cycle", "review"],
                   "Data collected": ["data", "survey", "metrics"],
                   "Results used for change": ["based on", "as a result", "revised", "changes"]},
         artifacts=[(M, "Completed annual administrative assessment / KPI review for Florida Atlantic Online (most recent 1-2 cycles)"),
                    (MEAS, "The actual results: online student survey results, retention/persistence/DFW reports"),
                    (IMP, "Closed-loop documentation: improvement actions taken because of those results, with dates and owners")],
         owners=[FAO, IEA]),
    dict(id="INS-05", n=5, required=M,
         text="The institution has a process for strategic planning and resource allocation for the online program, including human and financial resources.",
         anchors=[r"resource allocation", r"budget", r"incentive", r"stipend", r"responsible staff", r"\bfund", r"distance learning course fee"],
         terms=["online", "strategic", "planning", "allocation", "financial", "human", "responsible staff", "distance learning course fee", "support"],
         elements={"Planning process": ["strategic plan", "planning"],
                   "Human resource allocation": ["staff", "instructional design", "team"],
                   "Financial resource allocation": ["budget", "fund", "fee", "stipend", "incentive"]},
         artifacts=[(P, "Description of the annual budget-request / resource-allocation process for Florida Atlantic Online"),
                    (M, "Budget documents or allocation records tying resources (DL fee revenue, stipends, positions) to strategic-plan goals"),
                    (M, "Staffing plan / position allocations for instructional design, media, QA, and OESS")],
         owners=[FAO, BUD, PROV]),
    dict(id="INS-06", n=6, required=MEAS,
         text="The institution demonstrates sufficient resource allocation, including human and financial resources, in order to effectively support the mission of online education.",
         anchors=[r"resource allocation", r"budget", r"staffing", r"\bfund", r"capacity", r"\bfte\b"],
         terms=["sufficient", "online", "support", "instructional design", "media", "workload", "ratio", "demand"],
         artifacts=[(M, "Current budget and FTE staffing for Florida Atlantic Online / COCE units supporting online programs"),
                    (MEAS, "Capacity vs. demand data: courses developed per designer, ticket volumes, wait times, service backlogs"),
                    (MEAS, "Benchmark or trend comparison (online enrollment/SCH growth vs. support staffing) demonstrating sufficiency")],
         owners=[FAO, BUD, PROV]),
    dict(id="INS-07", must=[r"identit", r"verif", r"authenticat", r"proctor", r"multi-factor", r"single sign"], n=7, required=P,
         text="The institution has policy and guidelines that confirm a student who registers in an online course or program is the same student who participates and receives credit.",
         anchors=[r"identity", r"verif", r"authenticat", r"proctor", r"single sign", r"sso", r"multi-factor", r"mfa"],
         terms=["student", "online", "credential", "password", "login", "privacy", "fau net id", "account"],
         artifacts=[(P, "The specific identity-verification policy/procedure for distance education (secure login/SSO/MFA, proctoring, other methods) as required by SACSCOC"),
                    (M, "Evidence of implementation: MFA/SSO enforcement for Canvas, proctoring service contracts/usage, student notification of any verification fees"),
                    (P, "Confirm the adopted (not 'proposed') version of the Distance Learning Scope and Policies statement")],
         owners=[OIT_SEC, REG, FAO]),
    dict(id="INS-08", n=8, required=IMP,
         text="The online program's strategic plan is reviewed for its continuing relevance, and periodically improved and updated.",
         anchors=[r"strategic plan", r"review", r"updat", r"revis"],
         terms=["annual", "periodic", "progress", "relevance", "improve", "cycle", "2020", "2025", "prior plan"],
         artifacts=[(M, "Prior Florida Atlantic Online / COCE strategic plan (pre-2025) for comparison"),
                    (M, "Review calendar, progress reports or minutes documenting periodic review of the 2025-2030 plan"),
                    (IMP, "Revision log or memo describing what changed in the plan and why")],
         owners=[FAO, PROV]),

    # ------------------------------------------------------------ Technology Support (7)
    dict(id="TEC-01", n=1, required=MEAS,
         text="The technology delivery systems are highly reliable and operable with measurable standards such as system downtime tracking or task benchmarking.",
         anchors=[r"uptime", r"downtime", r"availability", r"reliab", r"outage", r"service level", r"sla"],
         terms=["canvas", "lms", "monitor", "incident", "benchmark", "percent", "99", "status"],
         artifacts=[(P, "Canvas (Instructure) SLA / contract uptime commitment and OIT service-level targets for course-delivery systems"),
                    (MEAS, "Annual LMS uptime/availability statistics and incident history (e.g., Instructure status reports + OIT incident log)"),
                    (M, "Description of reliability monitoring (status page, alerting, incident management process)")],
         owners=[OIT]),
    dict(id="TEC-02", n=2, required=M,
         text="A centralized technology system provides support for building and maintaining the online education infrastructure.",
         anchors=[r"canvas", r"lms", r"learning management", r"help desk", r"centraliz", r"infrastructure"],
         terms=["support", "oit", "online", "maintain", "tier", "24/7", "platform", "system"],
         artifacts=[(P, "OIT/LMS service description documenting ownership, administration and support model for Canvas and integrated tools"),
                    (M, "LMS administration records: integration inventory, change/maintenance calendar, support staffing")],
         owners=[OIT, FAO]),
    dict(id="TEC-03", n=3, required=M,
         text="A documented technology plan including electronic security measures is in place and operational in accordance with accreditation standards and regulatory requirements.",
         anchors=[r"security", r"technology plan", r"information security", r"classification", r"regulatory", r"accreditation"],
         terms=["policy", "data", "access", "vulnerab", "password", "ferpa", "protect", "privacy", "control"],
         artifacts=[(P, "The OIT technology plan / information security program document (not only individual policies)"),
                    (M, "Evidence the security program is operational: most recent security risk assessment, audit, or compliance review summary"),
                    (P, "Upload FAU Policy 12.7 and 12.2 files (referenced in the matrix but not supplied to this build) for passage-level verification")],
         owners=[OIT_SEC, OIT]),
    dict(id="TEC-04", n=4, required=M,
         text="Institutional technology systems related to online programs are administered in compliance with established data management practices including power protection, backups and disaster recovery.",
         anchors=[r"backup", r"disaster recovery", r"power", r"data management", r"redundan", r"recovery"],
         terms=["system", "data", "restore", "generator", "ups", "retention", "canvas", "cloud"],
         artifacts=[(P, "Backup and data-retention standard covering online-program systems (Canvas, Kaltura/video, proctoring, SIS integrations)"),
                    (M, "Disaster recovery documentation and most recent DR test/restore exercise results"),
                    (M, "Vendor (Instructure) data-protection and recovery commitments for hosted Canvas")],
         owners=[OIT, OIT_SEC]),
    dict(id="TEC-05", must=[r"continuity", r"contingency", r"disaster", r"disruption", r"data cent"], n=5, required=P,
         text="The institution has a contingency plan for continuance of data centers and support services in the event of prolonged service disruption.",
         anchors=[r"continuity", r"contingency", r"disruption", r"emergency", r"disaster", r"hurricane"],
         terms=["data center", "support services", "plan", "prolonged", "continuance", "remote"],
         artifacts=[(P, "Business continuity / continuity-of-operations plan (COOP) covering data centers and online support services"),
                    (M, "Evidence of a recent continuity exercise or activation (e.g., hurricane-season readiness) and lessons learned")],
         owners=[OIT, "FAU Emergency Management"]),
    dict(id="TEC-06", n=6, required=M,
         text="The course delivery technology is considered a mission-critical enterprise system and supported as such.",
         anchors=[r"mission[- ]critical", r"level 1", r"enterprise", r"learning support"],
         terms=["canvas", "lms", "system", "impair", "university", "support", "classification"],
         artifacts=[(P, "OIT system inventory or classification record showing Canvas/LMS is designated a Level 1 (mission-critical) system under Policy 12.7"),
                    (M, "Operational support records for the LMS consistent with Level 1 status (24/7 support contract, escalation procedures, SLA)")],
         owners=[OIT]),
    dict(id="TEC-07", n=7, required=M,
         text="Faculty, staff, and students are supported in the development and use of new technologies and skills.",
         anchors=[r"workshop", r"training", r"professional development", r"innovation hub", r"tutorial", r"orientation"],
         terms=["faculty", "staff", "students", "technolog", "ai", "multimedia", "tools", "skills", "lab"],
         elements={"Faculty support": ["faculty"], "Staff support": ["staff"], "Student support": ["student"]},
         artifacts=[(M, "Workshop/training catalog with delivery dates for faculty, staff AND students"),
                    (MEAS, "Participation/completion data (e.g., PLAIground, Faculty Lounge Live, Innovation Hub attendance)"),
                    (MEAS, "Post-session satisfaction/effectiveness survey results")],
         owners=[FACDEV, OIT, FAO]),

    # ------------------------------------------------------------ Course Development & Instructional Design (11)
    dict(id="CDID-01", n=1, required=M,
         text="Guidelines regarding minimum requirements for course development, design, and delivery of online instruction are in place, periodically reviewed and followed.",
         alt_text="Guidelines regarding minimum requirements for course development, design, and delivery are used.",
         anchors=[r"high[- ]quality", r"quality matters", r"\bqm\b", r"rubric", r"course design standard", r"minimum requirement"],
         terms=["course development", "design", "online", "instructional designer", "guideline", "review", "state"],
         artifacts=[(P, "FAU's internal online course design standards/checklist (the document instructional designers apply)"),
                    (M, "Completed course review records (QM/Florida HQ reviews) showing guidelines are followed"),
                    (M, "Evidence the guidelines themselves are periodically reviewed (revision history/date)")],
         owners=[COCE_ID, COCE_QA]),
    dict(id="CDID-02", n=2, required=M,
         text="Course development guidelines are in place and followed to ensure courses are designed to support student learning.",
         anchors=[r"learning objective", r"learning outcome", r"align", r"course orientation", r"assessment"],
         terms=["course", "design", "online", "instructional material", "interaction", "feedback", "quality matters", "standard"],
         artifacts=[(P, "Course development guideline/template requiring objectives, alignment, interaction, and assessment"),
                    (M, "Sample of completed course design reviews across colleges showing requirements were met")],
         owners=[COCE_ID, COLL]),
    dict(id="CDID-03", n=3, required=M, text=None, text_source="PENDING",
         hint="FAU matrix Evidence Requests sheet references: 'Samples/audit logs showing syllabi and instructional materials are actually reviewed against learning outcomes.' (topic hint only; not OLC wording)",
         artifacts=[(M, "Samples/audit logs showing syllabi and instructional materials are reviewed against learning outcomes (from FAU matrix request)")],
         owners=[COCE_ID, COLL]),
    dict(id="CDID-04", n=4, required=M,
         text="Student-centered instruction is considered during the course development process.",
         anchors=[r"student[- ]centered", r"student readiness", r"learner", r"engag"],
         terms=["course", "design", "development", "instructional", "strategies", "interaction", "support"],
         artifacts=[(P, "Design consultation template/rubric containing explicit student-centered criteria"),
                    (M, "Completed design-consultation notes or reviews showing criteria applied in real course builds")],
         owners=[COCE_ID]),
    dict(id="CDID-05", n=5, required=M, text=None, text_source="PENDING", artifacts=[], owners=[COCE_ID]),
    dict(id="CDID-06", n=6, required=M,
         text="Course design promotes both faculty and student engagement.",
         anchors=[r"interaction", r"engag"],
         terms=["faculty", "student", "course", "design", "substantive", "student-to-student", "learner interaction"],
         artifacts=[(M, "Course review results or LMS examples showing faculty-student and student-student engagement designed into courses")],
         owners=[COCE_ID, COLL]),
    dict(id="CDID-07", n=7, required=M, text=None, text_source="PENDING",
         hint="FAU matrix Evidence Requests sheet references: 'Copyright/Fair Use procedure, checklist and completed review evidence.' (topic hint only; not OLC wording)",
         artifacts=[(M, "Copyright/Fair Use procedure, checklist and completed review evidence (from FAU matrix request)")],
         owners=[COCE_ID, LIB, GC]),
    dict(id="CDID-08", n=8, required=P,
         text="Policies ensure instructional materials are easily accessible and usable across multiple operating systems and applications.",
         alt_text="Policies ensure instructional materials are easily accessible and usable across commonly used devices and assistive technologies.",
         anchors=[r"accessib", r"usabil", r"operating system", r"device", r"assistive", r"mobile", r"wcag"],
         terms=["instructional material", "course", "caption", "alternative", "platform", "browser", "policy"],
         artifacts=[(P, "FAU policy/standard requiring accessible, device-independent instructional materials (digital accessibility policy, WCAG level)"),
                    (M, "Accessibility/usability testing procedure used during course development")],
         owners=[SAS, COCE_ID, OIT]),
    dict(id="CDID-09", n=9, required=M, text=None, text_source="PENDING", artifacts=[], owners=[COCE_ID]),
    dict(id="CDID-10", n=10, required=M,
         text="Instructional materials are easily accessed by students with disabilities via alternative instructional strategies and/or referral to institutional resources.",
         anchors=[r"disabilit", r"accessib", r"accommodation", r"caption", r"alternative"],
         terms=["student accessibility services", "sas", "materials", "online", "referral", "format"],
         artifacts=[(P, "SAS accommodation workflow for online courses and referral language used in syllabi/Canvas"),
                    (M, "Examples of alternative formats/remediation delivered for online students; captioning request records")],
         owners=[SAS, COCE_ID]),
    dict(id="CDID-11", n=11, required=M,
         text="Curriculum development is a core responsibility for faculty; faculty are involved in development or decision making for online curriculum choices.",
         anchors=[r"faculty senate", r"curriculum", r"faculty member", r"course content"],
         terms=["online", "program", "department", "proposal", "responsib", "decision", "approval"],
         artifacts=[(M, "Faculty Senate / college curriculum committee minutes approving representative online programs or modality changes")],
         owners=[FSEN, COLL]),

    # ------------------------------------------------------------ Course Structure (7)
    dict(id="CS-01", n=1, required=M,
         text="The online course includes a syllabus outlining course objectives, learning outcomes, evaluation methods, books and supplies, technical and proctoring requirements, and related course information.",
         anchors=[r"syllab"],
         terms=["objectives", "outcomes", "evaluation", "books", "supplies", "technical", "proctor", "online", "course"],
         elements={"Objectives/outcomes": ["objective", "outcome"], "Evaluation methods": ["evaluation", "grading", "assessment"],
                   "Books and supplies": ["book", "textbook", "supplies", "materials"], "Technical requirements": ["technical", "technology requirement"],
                   "Proctoring requirements": ["proctor"]},
         artifacts=[(P, "Current FAU online syllabus template/checklist covering every OLC-listed element (incl. technical and proctoring requirements)"),
                    (M, "Random sample of online syllabi audited against the template")],
         owners=[PROV, COCE_ID, COLL]),
    dict(id="CS-02", n=2, required=M, text=None, text_source="PENDING", artifacts=[], owners=[COCE_ID]),
    dict(id="CS-03", n=3, required=M,
         text="Links or explanations of technical support are available in the course.",
         anchors=[r"technical support", r"help desk", r"tech support", r"canvas support", r"24/7"],
         terms=["course", "link", "canvas", "chat", "ticket", "tier 1", "support"],
         artifacts=[(M, "FAU Canvas course template / shell showing embedded technical-support links (screenshot or export)"),
                    (M, "Audit showing the template is used across online courses")],
         owners=[COCE_ID, OIT]),
    dict(id="CS-04", n=4, required=M,
         text="Course embedded technology is actively used to support achievement of learning outcomes.",
         anchors=[r"technolog", r"multimedia", r"tools", r"interactive"],
         terms=["learning outcome", "course", "embedded", "simulation", "video", "canvas", "achieve"],
         artifacts=[(M, "Course review standard (e.g., QM Standard 6) results showing tools support outcomes"),
                    (MEAS, "Tool usage analytics from Canvas/LTI tools linked to learning outcomes")],
         owners=[COCE_ID, OIT]),
    dict(id="CS-05", n=5, required=M,
         text="Opportunities/tools are provided to encourage student-student collaboration if appropriate.",
         anchors=[r"student-to-student", r"collaborat", r"peer", r"learner interaction", r"discussion"],
         terms=["student", "interaction", "group", "course", "tools"],
         artifacts=[(M, "Representative course artifacts or review reports showing collaboration opportunities/tools")],
         owners=[COCE_ID, COLL]),
    dict(id="CS-06", n=6, required=M, text=None, text_source="PENDING", artifacts=[], owners=[COCE_ID]),
    dict(id="CS-07", must=[r"netiquette", r"conduct", r"integrity", r"behavio"], n=7, required=M,
         text="Rules or standards for appropriate online student behavior are provided within the course.",
         anchors=[r"netiquette", r"code of conduct", r"student conduct", r"academic integrity", r"behavio"],
         terms=["student", "online", "course", "rules", "standards", "expectation"],
         artifacts=[(P, "Netiquette / online conduct statement in the syllabus or Canvas template; link to Student Code of Conduct and Academic Integrity regulation"),
                    (M, "Template audit showing the statement is present in online courses")],
         owners=[COCE_ID, SA]),

    # ------------------------------------------------------------ Teaching & Learning (4)
    dict(id="TL-01", n=1, required=M,
         text="Student-to-Student and Faculty-to-Student interaction are essential characteristics and are encouraged and facilitated.",
         anchors=[r"interaction", r"substantive", r"student-to-student"],
         terms=["faculty", "student", "regular", "online", "course", "engag"],
         artifacts=[(M, "Course-level implementation evidence of regular & substantive interaction (review results, LMS examples)"),
                    (MEAS, "RSI monitoring/audit results for online courses (federal RSI compliance)")],
         owners=[PROV, COCE_ID, COLL]),
    dict(id="TL-02", n=2, required=M, text=None, text_source="PENDING", artifacts=[], owners=[COCE_ID, COLL]),
    dict(id="TL-03", n=3, required=M,
         text="Feedback on student assignments and questions is constructive and provided in a timely manner.",
         anchors=[r"feedback", r"response time", r"timely"],
         terms=["assignment", "student", "faculty", "grade", "hours", "constructive", "assessment"],
         artifacts=[(P, "Stated faculty response-time / feedback expectation (policy, template statement)"),
                    (MEAS, "SPOT or survey items on feedback timeliness for online courses, with results")],
         owners=[PROV, COLL, IEA]),
    dict(id="TL-04", must=[r"librar"], n=4, required=P,
         text="Students are provided access to library professionals and resources to locate, analyze, evaluate, synthesize, and ethically use information resources.",
         anchors=[r"librar"],
         terms=["distance", "online", "research", "information", "databases", "librarian", "ask", "resources"],
         artifacts=[(P, "FAU Libraries distance/online learner services page (Ask-a-Librarian, research consultations, off-campus access)"),
                    (M, "Library instruction/consultation usage data for online students")],
         owners=[LIB]),

    # ------------------------------------------------------------ Faculty Support (9)
    dict(id="FAC-01", n=1, required=P,
         text="Faculty have access to university policy about intellectual property and it addresses online learning.",
         anchors=[r"intellectual property", r"\bip policy", r"copyright", r"ownership"],
         terms=["faculty", "distance learning", "online", "course", "policy 10.6", "university supported work"],
         artifacts=[(P, "Current FAU Policy 10.6 Intellectual Property (link resolves) and the adopted distance-learning IP section"),
                    (M, "Evidence faculty are directed to the IP provisions during online course development (MOU/agreement template, onboarding)")],
         owners=[OTD, PROV, FAO]),
    dict(id="FAC-02", n=2, required=M,
         text="The institution ensures faculty receive training, assistance, and support to prepare faculty for course development.",
         anchors=[r"training", r"workshop", r"professional development", r"instructional design"],
         terms=["faculty", "course development", "online", "support", "assist", "quality matters", "prepare"],
         artifacts=[(M, "Course development onboarding workflow and records showing faculty were trained/supported before development"),
                    (MEAS, "Participation/completion counts per term")],
         owners=[COCE_ID, FACDEV]),
    dict(id="FAC-03", n=3, required=M, text=None, text_source="PENDING", artifacts=[], owners=[FACDEV]),
    dict(id="FAC-04", n=4, required=P,
         text="Faculty have access to training, online resources and support related to Fair Use, plagiarism, and other legal and ethical concepts.",
         anchors=[r"fair use", r"plagiar", r"copyright", r"academic integrity", r"ethical"],
         terms=["faculty", "training", "resources", "legal", "support", "turnitin"],
         artifacts=[(P, "Faculty-facing Fair Use/copyright guidance (Libraries copyright guide) and academic-integrity resources"),
                    (M, "Workshop records on copyright/fair use/academic integrity for online faculty")],
         owners=[LIB, FACDEV, GC]),
    dict(id="FAC-05", n=5, required=M,
         text="The institution ensures faculty receive training, assistance, and support to prepare faculty for teaching online.",
         anchors=[r"training", r"workshop", r"professional development", r"orientation"],
         terms=["faculty", "teaching online", "online", "pedagogy", "prepare", "complete", "distance learning"],
         artifacts=[(P, "Written requirement that faculty complete online-teaching training before teaching online"),
                    (M, "Training completion records and the enforcement/assignment workflow"),
                    (MEAS, "Count of faculty trained (baseline for the plan's +10% target) and trend")],
         owners=[FACDEV, COLL, FAO]),
    dict(id="FAC-06", n=6, required=M, text=None, text_source="PENDING", artifacts=[], owners=[FACDEV]),
    dict(id="FAC-07", n=7, required=P,
         text="Technical assistance is provided for faculty during online teaching.",
         anchors=[r"technical assistance", r"technical support", r"help desk", r"open lab", r"canvas support", r"idesign@", r"request help"],
         terms=["faculty", "teaching", "online", "canvas", "request", "ticket"],
         artifacts=[(P, "Faculty technical-support service description (OIT + COCE Open Lab)"),
                    (MEAS, "Ticket volume/response-time metrics for faculty requests")],
         owners=[OIT, FAO]),
    dict(id="FAC-08", n=8, required=M,
         text="Clear standards are established for faculty engagement and expectations around online teaching and periodically reviewed.",
         anchors=[r"expectation", r"standard", r"faculty responsib", r"engagement"],
         terms=["faculty", "online teaching", "interaction", "response", "review", "periodic"],
         artifacts=[(P, "Written online-teaching expectations for faculty (response time, presence, RSI)"),
                    (M, "Evidence the expectations are periodically reviewed (revision dates, committee review)")],
         owners=[PROV, COLL, FAO]),
    dict(id="FAC-09", n=9, required=P,
         text="Faculty are informed about institutionally supported education technologies and the selection and use of new tools.",
         anchors=[r"technolog", r"tools", r"innovation", r"supported"],
         terms=["faculty", "informed", "new", "select", "approved", "canvas", "ai", "hub"],
         artifacts=[(P, "Published list of institutionally supported teaching tools and the tool-request/vetting process"),
                    (M, "Faculty communications announcing new/retired tools")],
         owners=[OIT, FAO]),

    # ------------------------------------------------------------ Learner Support (15)
    dict(id="LEA-01", n=1, required=M,
         text="Before starting an online program, students are advised about the program to determine if they have access to minimum technology skills and equipment required.",
         anchors=[r"technology requirement", r"minimum", r"equipment", r"readiness", r"device", r"computer requirement"],
         terms=["student", "online", "before", "advise", "skills", "internet", "program"],
         artifacts=[(P, "Pre-enrollment technology requirements / online readiness self-assessment page"),
                    (M, "Advising/onboarding step where online students are shown those requirements (OESS script, checklist)")],
         owners=[OESS, ADM]),
    dict(id="LEA-02", n=2, required=P,
         text="Before starting an online program, students have access to information about programs, including admission requirements, tuition and fees, books and supplies, technical and proctoring requirements, and student support services.",
         anchors=[r"admission", r"tuition", r"fees", r"program information"],
         terms=["online", "program", "books", "technical", "proctor", "support services", "requirements"],
         elements={"Admission requirements": ["admission"], "Tuition and fees": ["tuition", "fee"], "Books and supplies": ["book", "supplies"],
                   "Technical requirements": ["technical", "technology"], "Proctoring requirements": ["proctor"], "Support services": ["support"]},
         artifacts=[(P, "Per-program pre-enrollment page set (FAU Online program pages) showing each required element, esp. tuition/fees and proctoring requirements"),
                    (M, "Audit checklist confirming every online program page carries all elements")],
         owners=[OESS, ADM, FAO]),
    dict(id="LEA-03", n=3, required=P,
         text="Students have access to required course materials in print and/or digital format, such as ISBN numbers, suppliers, and delivery modes prior to course enrollment.",
         anchors=[r"isbn", r"textbook", r"course materials", r"bookstore", r"adoption"],
         terms=["prior", "enrollment", "digital", "print", "supplier"],
         artifacts=[(P, "Textbook adoption/posting process under Florida textbook affordability statute (s. 1004.085) and the student-facing lookup"),
                    (M, "Compliance report showing materials posted before registration")],
         owners=[BOOK, PROV]),
    dict(id="LEA-04", n=4, required=M,
         text="Opportunities are provided to engage students with the program and institution to minimize feelings of isolation.",
         anchors=[r"sense of community", r"engag", r"virtual event", r"advisory board", r"isolation", r"peer-to-peer"],
         terms=["online student", "community", "events", "clubs", "students"],
         artifacts=[(M, "Event calendar/records of virtual engagement events with attendance"),
                    (M, "Online Student Advisory Board roster, agendas, minutes"),
                    (MEAS, "Online student survey items on belonging/isolation and results")],
         owners=[OESS, SA]),
    dict(id="LEA-05", n=5, required=M,
         text="Program demonstrates a student-centered focus addressing online student needs rather than fitting existing on-campus services to online students.",
         anchors=[r"online learner", r"online student", r"tailored", r"student-centered"],
         terms=["needs", "support services", "service gaps", "equivalent", "data", "experience"],
         artifacts=[(M, "Inventory of services designed specifically for online learners (eTutoring, online proctoring help, equipment loan, OESS)"),
                    (IMP, "Service changes made because of online-student data/feedback")],
         owners=[OESS, SA]),
    dict(id="LEA-06", n=6, required=P,
         text="Institutional communications provide clear and timely information on where to enlist assistance.",
         anchors=[r"contact", r"assistance", r"help", r"resources", r"support"],
         terms=["students", "directory", "where", "advising", "tutoring", "online", "email"],
         artifacts=[(P, "Central student-resources directory and online-student welcome/onboarding communications"),
                    (M, "Communication calendar for online students (term-start emails, reminders)")],
         owners=[OESS, SA, COMM]),
    dict(id="LEA-07", n=7, required=P,
         text="Students are provided noninstructional support services such as admission, financial assistance, registration/enrollment, etc.",
         anchors=[r"financial aid", r"admission", r"registration", r"enrollment", r"registrar"],
         terms=["students", "online", "services", "support", "advis", "billing"],
         artifacts=[(P, "Pages documenting remote access to admissions, financial aid, registration for online students"),
                    (MEAS, "Service access metrics for online students (virtual appointments, response times)")],
         owners=[ADM, FA, REG, OESS]),
    dict(id="LEA-08", n=8, required=P,
         text="Throughout the course/program, students have access to appropriate technical assistance and technical support staff.",
         anchors=[r"technical support", r"help desk", r"24/7", r"tech support", r"technical assistance"],
         terms=["students", "canvas", "chat", "ticket", "tier 1", "support"],
         artifacts=[(P, "Student technical-support service description (hours, channels)"),
                    (MEAS, "Support SLA and ticket resolution metrics for students")],
         owners=[OIT]),
    dict(id="LEA-09", n=9, required=MEAS,
         text="Students have access to effective academic and career counseling.",
         anchors=[r"advis", r"career", r"counsel"],
         terms=["academic", "online", "students", "success network", "appointment", "virtual"],
         artifacts=[(P, "Documentation of remote/virtual academic advising and career services for online students"),
                    (MEAS, "Effectiveness evidence: advising satisfaction survey results, appointment/usage data for online students, outcome measures")],
         owners=["Academic Advising", CAREER, OESS]),
    dict(id="LEA-10", n=10, required=P,
         text="Students have access to personal counseling.",
         anchors=[r"counseling", r"psychological", r"caps", r"mental health", r"telehealth"],
         terms=["students", "online", "virtual", "remote", "personal"],
         artifacts=[(P, "CAPS page showing telehealth/remote access available to fully online students (incl. out-of-state limits)"),
                    (M, "Usage data for remote counseling by online students")],
         owners=[CAPS, SA]),
    dict(id="LEA-11", n=11, required=P,
         text="Policy, processes and resources are in place to support students with disabilities.",
         anchors=[r"disabilit", r"accommodation", r"student accessibility services", r"\bsas\b", r"accessib"],
         terms=["students", "policy", "process", "resources", "online", "register"],
         artifacts=[(P, "SAS policy and online accommodation request procedure"),
                    (M, "SAS usage data and accommodation outcomes for online students")],
         owners=[SAS]),
    dict(id="LEA-12", n=12, required=P, text=None, text_source="PENDING", artifacts=[], owners=[OESS]),
    dict(id="LEA-13", must=[r"librar", r"interlibrary", r"database"], n=13, required=P,
         text="Throughout the course/program, students have access to training and information needed to secure required materials through electronic databases, interlibrary loans, government archives and new services.",
         anchors=[r"interlibrary", r"database", r"librar", r"archive"],
         terms=["students", "online", "distance", "training", "electronic", "access"],
         artifacts=[(P, "FAU Libraries distance-learner page covering databases, ILL/document delivery, and research training"),
                    (M, "ILL/database usage by distance students; library instruction sessions for online courses")],
         owners=[LIB]),
    dict(id="LEA-14", n=14, required=P,
         text="Online tutoring is available as a learning resource.",
         anchors=[r"tutor"],
         terms=["online", "etutoring", "virtual", "class", "math learning center", "students"],
         artifacts=[(P, "Online/eTutoring service description (CLASS, Math Learning Center, eTutoring consortium)"),
                    (MEAS, "Online tutoring usage and outcome data")],
         owners=[CLASS, OESS]),
    dict(id="LEA-15", n=15, required=P,
         text="The institution and/or instructor provides guidance/tutorials for students in use of all technologies used for course delivery.",
         anchors=[r"tutorial", r"guide", r"orientation", r"how to", r"canvas"],
         terms=["students", "technolog", "course delivery", "student guide", "training"],
         artifacts=[(P, "Student Canvas orientation / tutorial inventory mapped to every required course-delivery tool (Canvas, proctoring, video, publisher tools)")],
         owners=[OIT, FAO]),

    # ------------------------------------------------------------ Evaluation & Assessment (9)
    dict(id="EVA-01", n=1, required=M,
         text="The program is assessed through an evaluation process that applies specific established standards.",
         anchors=[r"program evaluation", r"program review", r"evaluat", r"standards", r"quality matters"],
         terms=["program", "online", "process", "accreditation", "sacscoc", "review"],
         artifacts=[(P, "Academic program review procedure applying to online programs (standards used)"),
                    (M, "Program review schedule and a completed review for an online program")],
         owners=[IEA, PROV, COLL]),
    dict(id="EVA-02", n=2, required=MEAS, text=None, text_source="PENDING", artifacts=[], owners=[IEA]),
    dict(id="EVA-03", n=3, required=MEAS,
         text="Intended learning outcomes at course and program level are reviewed regularly for alignment, clarity, utility, appropriateness and effectiveness.",
         alt_text="Intended learning outcomes at course and program level are reviewed regularly to ensure clarity, utility and appropriateness.",
         anchors=[r"learning outcome", r"outcomes assessment", r"assessment"],
         terms=["course", "program", "review", "regular", "alignment", "effectiveness", "equivalent"],
         artifacts=[(M, "Academic learning compact / assessment-plan review cycle documentation"),
                    (MEAS, "Recent program learning-outcomes assessment reports including online programs"),
                    (IMP, "Changes made from outcomes assessment")],
         owners=[IEA, COLL]),
    dict(id="EVA-04", n=4, required=M,
         text="Course evaluations collect feedback on effectiveness of instruction and quality of the course.",
         anchors=[r"spot", r"course evaluation", r"student perception", r"evaluation"],
         terms=["instruction", "quality", "course", "feedback", "semester", "distance learning"],
         artifacts=[(P, "SPOT instrument (item list)"),
                    (MEAS, "SPOT response rates/results for online courses"),
                    (IMP, "Examples of course improvements made from SPOT findings")],
         owners=[IEA, PROV]),
    dict(id="EVA-05", n=5, required=M,
         text="A process is in place and followed for institutional assessment of faculty online teaching performance.",
         anchors=[r"teaching performance", r"instructional effectiveness", r"spot", r"faculty evaluation", r"annual evaluation"],
         terms=["faculty", "online", "assess", "teaching", "process", "distance learning"],
         artifacts=[(P, "Faculty annual evaluation / peer observation process covering online teaching"),
                    (M, "Completed examples (redacted) or process compliance records")],
         owners=[PROV, COLL, IEA]),
    dict(id="EVA-06", n=6, required=MEAS, text=None, text_source="PENDING", artifacts=[], owners=[IEA]),
    dict(id="EVA-07", n=7, required=MEAS,
         text="A process is in place and followed for assessment of student retention in online courses and programs.",
         alt_text="A process is in place and followed for assessment of student retention in online programs.",
         anchors=[r"retention", r"persistence", r"withdrawal", r"dfw", r"graduation rate"],
         terms=["online", "students", "rates", "monitor", "tracking", "semester", "graduation"],
         artifacts=[(MEAS, "Recurring online retention/persistence/DFW reports or dashboards (with online vs. on-campus comparison)"),
                    (IMP, "Documented interventions triggered by retention findings and their outcomes")],
         owners=[OESS, IEA]),
    dict(id="EVA-08", n=8, required=MEAS,
         text="Program demonstrates compliance and review of accessibility standards (Section 508/WCAG/etc.).",
         anchors=[r"wcag", r"section 508", r"accessib", r"\bada\b"],
         terms=["review", "compliance", "standards", "audit", "course", "online", "usability"],
         artifacts=[(P, "Formal accessibility compliance review process and standard (WCAG 2.1 AA / Title II ADA rule)"),
                    (MEAS, "Accessibility audit results for online courses/programs and remediation records")],
         owners=[SAS, COCE_QA, OIT]),
    dict(id="EVA-09", n=9, required=MEAS, text=None, text_source="PENDING", artifacts=[], owners=[IEA]),
]
